spring.application.name=foodsave-backend

spring.data.mongodb.uri=momgodb
spring.data.mongodb.database=foodsave

server.port=8080

# ================================
# Ollama
# ================================

ollama.url=http://localhost:11434
ollama.model=granite4
ollama.embedding-model=nomic-embed-text

# ========================================
# LOGGING
# ========================================

logging.level.com.foodsave=INFO