package foodsave.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "knowledge_documents")
public class KnowledgeDocument {

    @Id
    private String id;

    private String title;

    private String content;

    private String category;

    private String source;

    private List<String> tags;

    /*
     * Vector embedding generated by Ollama.
     *
     * nomic-embed-text produces a numerical vector
     * representing the semantic meaning of the document.
     */
    private List<Double> embedding;

    private LocalDateTime createdAt;
}